# This is a basic workflow to help you get started with Actions

name: build-vertio-automotive

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Create Build Environment
        run: |
          echo Install build tools
          
          sudo apt install gcc g++ make cmake
          sudo apt install libpgm-5.2-0 libpgm-dev

          
      # Runs a single command using the runners shell
      - name: Build zero
        run: |
          wget https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz 
          tar -xf zeromq-4.3.4.tar.gz 
          cd zeromq-4.3.4
          ./configure --with-pgm 
          make 
          sudo make install
          
      # Runs a set of commands using the runners shell
      - name: Create Build Environment 2
        run: |
          echo Install virglrenderer
          
          sudo apt install libvirglrenderer1 libvirglrenderer-dev
          
          echo Install Weston compositor
          
          sudo apt install libvirglrenderer1 libvirglrenderer-dev
          sudo apt install libjpeg-dev libwebp-dev libsystemd-dev libpam-dev libva-dev freerdp2-dev \
           libxcb-composite0-dev liblcms2-dev libcolord-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libpipewire-0.2-dev \
           libxml2-dev meson
          
          
          
          
