name: demo
on: 
  push:
  pull_request:
  release:
jobs:
  preparation:
    runs-on: ubuntu-20.04
    steps:
      # Runs a set of commands using the runners shell
      - name: Create Build Environment
        run: |
          echo Install build tools
          
          sudo apt install gcc g++ make cmake
          sudo apt install libpgm-5.2-0 libpgm-dev
      # Runs a single command using the runners shell
      - name: Build zero
        run: |
          wget https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz 
          tar -xf zeromq-4.3.4.tar.gz 
          cd zeromq-4.3.4
          ./configure --with-pgm 
          make 
          sudo make install
          
      # Runs a set of commands using the runners shell
      - name: Create Build Environment 2
        run: |
          echo Install virglrenderer
          
          sudo apt update
          
          echo update done------------------------------------------------------------------------
          
          sudo apt install libvirglrenderer1 libvirglrenderer-dev
          
          echo Install Weston compositor
          
          sudo apt install libvirglrenderer1 libvirglrenderer-dev
          sudo apt install libjpeg-dev libwebp-dev libsystemd-dev libpam-dev libva-dev freerdp2-dev libxcb-composite0-dev liblcms2-dev libcolord-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libpipewire-0.2-dev libxml2-dev meson
          sudo apt install libxkbcommon-x11-dev libpixman-1-dev libinput-dev libdrm-dev wayland-protocols  libcairo2-dev libpango1.0-dev libdbus-1-dev libgbm-dev libxcursor-dev
          sudo apt install llvm libwayland-egl-backend-dev libxcb-glx0-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev \ 
                 libxcb-present-dev libxshmfence-dev libgbm-dev libsdl2-dev libgtk-3-dev libgles2-mesa-dev libpixman-1-dev \ 
                 libtool autoconf libdrm-dev python libinput-dev libwayland-egl-backend-dev glmark2-es2-wayland
                 
          cd ..
          wget https://github.com/wayland-project/weston/archive/8.0.93.tar.gz 
          tar -xf 8.0.93.tar.gz 
          cd weston-8.0.93
          meson build/
          sudo ninja -C build/ install
          
          cd .. 
         wget https://archive.mesa3d.org//mesa-18.2.0.tar.xz 
          tar -xf mesa-18.2.0.tar.xz 
          cd mesa-18.2.0/ 

          ./configure --prefix=/usr/lib/mesa-virtio --exec_prefix=/usr/lib/mesa-virtio --libdir=/usr/lib/mesa-virtio \ 
                                                    --includedir=/usr/include/mesa-virtio --sysconfdir=/etc/mesa-virtio --datadir=/usr/share/mesa-virtio \ 
                                                    --with-dri-drivers=swrast --with-gallium-drivers=swrast,virgl \
                                                    --enable-dri3=yes --with-platforms=drm,wayland,x11 --disable-glx
          make
          sudo make install
          
