name: demo
on: 
  push:
  pull_request:
  release:
jobs:
  preparation:
    runs-on: self-hosted
    steps:
      # Runs a set of commands using the runners shell
      - name: Create Build Environment
        run: |
          echo Install build tools
          
          pwd
          ls -la
          cd /home/tinhembedded/workspace/
          ls -la
          
          
