name: demo
on: 
  push:
  pull_request:
  release:
jobs:
  reciever:
    name: run on reciever 
    runs-on: self-hosted
    steps:
        # Runs a set of commands using the runners shell
        - name: Create Build Environment 2
          run: |
            cd 
            ls -la


          
          
