name: demo
on: 
  push:
  pull_request:
  release:
jobs:
  reciever:
    name: run on reciever 
    runs-on: self-hosted
    steps:
        # Runs a set of commands using the runners shell
        - name: Create Build Environment 2
          run: |
            echo Install build tools
            sudo modprobe virtio-lo
            sudo modprobe virtio_gpu
            ls -la
        
  sender:    
    name: run on senderer
    runs-on: self-hosted-2
    steps:
      # Runs a set of commands using the runners shell
      - name: Create Build Environment
        run: |
          echo Sender run
          ls -la
          


          
          
