name: demo_tab2
on: 
  push:
  pull_request:
  release:
jobs:
  preparation:
    runs-on: self-hosted
    steps:
      # Runs a set of commands using the runners shell
      - name: Create Build Environment 2
        run: |
          echo Install build tools
          ls -la
          sudo modprobe virtio-lo
          1
          sudo modprobe virtio_gpu
          rvgpu-renderer -b 1280x720@0,0 -p 55667
