name: demo_tab2
on: 
  push:
  pull_request:
  release:
jobs:
  preparation:
    runs-on: self-hosted
    steps:
      # Runs a set of commands using the runners shell
      - name: Create Build Environment 2
        run: |
          echo Install build tools
          
          pwd
          ls -la
          cd /home/tinhembedded/workspace/2022
          ls -la
